name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to FTP
      run: |
        FTP_SERVER="ftp.arbobtechteam.com"
        FTP_USER="u296449670.geomapink.com"
        FTP_PASS="Shah@230"
        LOCAL_DIR="./"  # Deploy the entire repository
        REMOTE_DIR="public_html"

        lftp -u "${FTP_USER}","${FTP_PASS}" "${FTP_SERVER}" <<EOF
        mirror --reverse --delete --verbose "${LOCAL_DIR}" "${REMOTE_DIR}"
        bye
        EOF
